-- Migration 003: Proactive alerts table + AI usage tracking
-- UP

-- Proactive alerts generated by the system or AI
CREATE TABLE proactive_alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  household_id UUID NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  priority TEXT NOT NULL CHECK (priority IN ('high', 'medium', 'low')),
  category TEXT NOT NULL CHECK (category IN ('identite', 'sante', 'fiscal', 'caf', 'scolarite', 'budget')),
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  action_url TEXT,
  due_date DATE,
  dismissed BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(),
  expires_at TIMESTAMPTZ
);

-- AI usage tracking per household per month
CREATE TABLE ai_usage (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  household_id UUID NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  month DATE NOT NULL, -- first day of month
  call_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(household_id, month)
);

-- AI monthly summaries cache
CREATE TABLE ai_monthly_summaries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  household_id UUID NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  month DATE NOT NULL,
  health TEXT NOT NULL,
  development TEXT NOT NULL,
  budget TEXT NOT NULL,
  admin TEXT NOT NULL,
  priorities TEXT[] NOT NULL DEFAULT '{}',
  generated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(household_id, month)
);

-- RLS
ALTER TABLE proactive_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_monthly_summaries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own alerts" ON proactive_alerts
  FOR ALL USING (household_id IN (SELECT user_household_ids()));

CREATE POLICY "Users see own AI usage" ON ai_usage
  FOR ALL USING (household_id IN (SELECT user_household_ids()));

CREATE POLICY "Users manage own summaries" ON ai_monthly_summaries
  FOR ALL USING (household_id IN (SELECT user_household_ids()));

-- DOWN
-- DROP TABLE ai_monthly_summaries;
-- DROP TABLE ai_usage;
-- DROP TABLE proactive_alerts;
